// constants/categories.ts
import { CategoryUI } from "@/types/category";

export const CATEGORIES_DATA: CategoryUI[] = [
    {
        id: "uuid-1",
        name: "Technology",
        slug: "technology",
        description: "AI, Web Dev, and Gadget summits.",
        iconName: "Zap",
        color: "from-blue-500 to-cyan-500",
        _count: { events: 120 },
        isActive: true,
        isDeleted: false,
    },
    {
        id: "uuid-2",
        name: "Business",
        slug: "business",
        description: "Networking and startup pitch decks.",
        iconName: "TrendingUp",
        color: "from-indigo-500 to-purple-500",
        _count: { events: 85 },
        isActive: true,
        isDeleted: false,
    },
    {
        id: "uuid-3",
        name: "Community",
        slug: "community",
        description: "Meetups and social gatherings.",
        iconName: "Users",
        color: "from-rose-500 to-orange-500",
        _count: { events: 200 },
        isActive: true,
        isDeleted: false,
    },
    {
        id: "uuid-43",
        name: "Workshops",
        slug: "workshops",
        description: "Hands-on learning and masterclasses.",
        iconName: "Calendar",
        color: "from-emerald-500 to-teal-500",
        _count: { events: 48 },
        isActive: true,
        isDeleted: false,
    },
    {
        id: "uuid-44",
        name: "Workshops",
        slug: "workshops",
        description: "Hands-on learning and masterclasses.",
        iconName: "Calendar",
        color: "from-emerald-500 to-teal-500",
        _count: { events: 47 },
        isActive: true,
        isDeleted: false,
    },
    {
        id: "uuid-45",
        name: "Workshops",
        slug: "workshops",
        description: "Hands-on learning and masterclasses.",
        iconName: "Calendar",
        color: "from-emerald-500 to-teal-500",
        _count: { events: 46 },
        isActive: true,
        isDeleted: false,
    },
];